spring:
  application:
    name: audit-service
server:
  port: 8082

# Local profile
---
spring:
  config:
    activate:
      on-profile: local
  # elasticsearch:
  #   uris: http://localhost:9200
  #   username: elastic
  #   password: changeme   # update as per your ES setup

# Docker profile
---
spring:
  config:
    activate:
      on-profile: docker
  # elasticsearch:
  #   uris: http://elasticsearch:9200
  #   username: elastic
  #   password: changeme
