
# Spring Boot Audit Service

server:
  port: 8082

spring:
  application:
    name: audit-service

elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: changeme

logging:
  level:
    org.springframework: INFO
    com.example.auditservice: DEBUG
