# Spring Boot API Gateway

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # Example route config
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**, /roles/**, /permissions/**
          filters:
            - StripPrefix=1 
        - id: audit-service
          uri: http://localhost:8082
          predicates:
            - Path=/audit/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework: INFO
    com.example.gateway: DEBUG
