# Spring Boot User Service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: user-service

logging:
  level:
    org.springframework: INFO
    com.example.userservice: DEBUG
