spring:
  application:
    name: user-service
server:
  port: 8081

# Local profile
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: userdb
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

# Docker profile
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: userdb
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true