name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build all modules with Maven
        run: mvn -B clean verify

      - name: Run User Service Tests
        run: mvn -pl user-service test

      - name: Run Audit Service Tests
        run: mvn -pl audit-service test

      - name: Run Gateway Tests
        run: mvn -pl gateway test

      - name: Lint Backend (Checkstyle)
        run: mvn checkstyle:check

      - name: Build Docker Images
        run: |
          docker build -t user-service ./user-service
          docker build -t audit-service ./audit-service
          docker build -t gateway ./gateway